### ISSUE TITLE
[fr] add telugu layout unexpected keyboard

### ISSUE THREAD

**Issue by jindamvani** [androidtweak/Indic-Keyboard#2]
@jishnu7 If possible can you please add telugu layout on [unexpected keyboard](https://github.com/Julow/Unexpected-Keyboard). https://github.com/Julow/Unexpected-Keyboard/issues/355 Thought to send an email but it seems to be too much. Thank you.

**Comment by jishnu7** [comment]
Hi @jindamvani I'm hearing about the keyboard for the first time. Since I'm not a user, I won't be able to help you regarding that. 

Since the ticket is not related to Indic Keyboard, closing the ticket.

Thanks
